// Generated by https://quicktype.io

import { FootballField } from "./FootballFields";
import { ComplexSchedule } from "./ComplexesSchedules";

export interface ComplexesResponse {
  complexes: Complex[];
}

export interface Complex {
  _id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  createdAt: string;
  updatedAt: string;
  ownerId: string;
  FootballFields: FootballField[];
  ComplexSchedules: ComplexSchedule[];
}

// Generated by https://quicktype.io

export interface PostComplexResponse {
  newComplex: Complex;
}

export interface DeleteComplexResponse {
  deletedComplex: Complex;
}

export interface PostComplexBody {
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  ownerId: string;
}
