// Generated by https://quicktype.io

import { FootballField } from "./FootballFields";
import { ComplexSchedule } from "./ComplexesSchedules";
import { Asset } from "react-native-image-picker";

export interface ComplexesResponse {
  complexes: Complex[];
}

export interface Complex {
  _id: string;
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  createdAt: string;
  updatedAt: string;
  ownerId: string;
  FootballFields: FootballField[];
  ComplexSchedules: ComplexSchedule[];
  mainPictureKey: string;
  mainPictureURL: { imageURL: string; imageKey: string };
  extraPicturesKeys: string[];
  extraPicturesURLs: { imageURL: string; imageKey: string }[];
}

// Generated by https://quicktype.io

export interface PostComplexResponse {
  newComplex: Complex;
}

export interface PutComplexResponse {
  updatedComplex: Complex;
}

export interface DeleteComplexResponse {
  deletedComplex: Complex;
}

export interface PostComplexBody {
  name: string;
  address: string;
  latitude: number;
  longitude: number;
  ownerId: string;
  complexPicture: Asset;
}

// Generated by https://quicktype.io

export interface GetComplexImageResponse {
  imageURL: { imageURL: string; imageKey: string };
}

export interface GetComplexExtraPicturesResponse {
  extraPicturesURLs: { imageURL: string; imageKey: string }[];
}
