// Generated by https://quicktype.io

export interface PostMultipleSchedulesResponse {
  newComplexSchedules: ComplexSchedule[];
}

export interface ComplexSchedule {
  _id: string;
  weekDays: number[];
  openingTime: string;
  closingTime: string;
  sport: string;
  complexId: string;
  updatedAt: string;
  createdAt: string;
}
