import { Turn } from "./Turns";

export interface FootballField {
  _id: string;
  fieldNumber: number;
  createdAt: string;
  updatedAt: string;
  complexId: string;
  Turns?: Turn[];
}

// Generated by https://quicktype.io

export interface PostMultipleFieldsResponse {
  newFootballFields: NewFootballField[];
}

export interface NewFootballField {
  _id: string;
  fieldNumber: number;
  complexId: string;
  updatedAt: string;
  createdAt: string;
}
