// Generated by https://quicktype.io

export interface PlayersResponse {
  players: Player[];
}

export interface PlayerResponse {
  player: Player;
}

export interface Player {
  _id: string;
  name: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  createdAt: string;
  updatedAt: string;
}
