// Generated by https://quicktype.io

import { Owner } from "./Owners";

export interface TurnsResponse {
  turns: Turn[];
}

// Generated by https://quicktype.io

export interface CreateTurnResponse {
  newTurn: Turn;
}

export interface Turn {
  _id: string;
  startDate: string;
  endDate: string;
  confirmed: boolean;
  cancelled: null;
  playerName: string;
  playerLastName: string;
  playerEmail: string;
  playerPhoneNumber: string;
  createdAt: string;
  updatedAt: string;
  fieldId: string;
  playerId: null;
  complexId: string;
  complexOwnerId: string;
  Player: null;
  Owner: Owner;
}
